SMS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('adminapp.urls')),
    path('facultyapp/', include('facultyapp.urls')),
    path('studentapp/', include('studentapp.urls')),
]

adminapp/SMS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('adminapp.urls')),
    path('facultyapp/', include('facultyapp.urls')),
    path('studentapp/', include('studentapp.urls')),
]

adminapp/facultyapp/urls.py
from django.urls import path, include
from . import views
app_name = 'facultyapp'
urlpatterns = [
    path('FacultyHomePage/', views.facultyhomepage, name="FacultyHomePage"),
    path('add_post/', views.add_post, name='add_post'),
    path('<int:pk>/delete/', views.delete_post, name='delete_post'),
    path('add_course/', views.add_course, name='add_course'),
    path('add_view_student_list/', views.view_student_list, name='add_view_student_list'),
    path('post_marks/', views.post_marks, name='post_marks'),
]

adminapp/urls.py
from django.urls import path, include
from . import views
from .views import feedback_view

urlpatterns = [
    path('', views.projecthomepage, name='projecthomepage'),
    path('printpagecall/', views.printpagecall, name='printpagecall'),
    path('printpagelogic/', views.printpagelogic, name='printpagelogic'),
    path('exceptionpagecall/', views.exceptionpagecall, name='exceptionpagecall'),
    path('exceptionpagelogic/', views.exceptionpagelogic, name='exceptionpagelogic'),
    path('randompagecall/', views.randompagecall, name='randompagecall'),
    path('randomlogic/', views.randomlogic, name='randomlogic'),
    path('calculatorpagecall/', views.calculatorpagecall, name='calculatorpagecall'),
    path('calculatorlogic/', views.calculatorlogic, name='calculatorlogic'),
    path('datetimepagecall/', views.datetimepagecall, name='datetimepagecall'),
    path('datetimepagelogic/', views.datetimepagelogic, name='datetimepagelogic'),
    path('add_task/', views.add_task, name='add_task'),
    path('<int:pk>/delete/', views.delete_task, name='delete_task'),
    path('register/', views.UserRegisterPageCall, name='UserRegisterPageCall'),
    path('register/submit/', views.UserRegisterLogic, name='UserRegisterLogic'),
    path('logout/', views.user_logout, name='logout'),
    path('login/', views.user_login, name='login'),
    path('add_post/', views.add_post, name='add_post'),
    path('<int:pk>/delete/', views.delete_post, name='delete_post'),
    path('facultyhomepage/', views.facultyhomepage, name='facultyhomepage'),
    path('studenthomepage/', views.studenthomepage, name='studenthomepage'),
    path('add_details/', views.add_student, name='add_details'),
    path('show_details/', views.student_list, name='show_details'),
    path('upload_file/', views.upload_file, name='upload_file'),
    path('feedback_form', views.feedback_view, name='feedback_form'),
    path('feedback_success/', views.feedback_success, name='feedback_success'),
]

adminapp/facultyapp/models.py
# faculty/models.py

from django.db import models

from adminapp.models import StudentList


class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class AddCourse(models.Model):
    COURSE_CHOICES = [
        ('AOOP', 'Advanced Object-Oriented Programming'),
        ('PFSD', 'Python Full Stack Development'),
    ]
    SECTION_CHOICES = [
        ('S11', 'SECTION S11'),
        ('S12', 'SECTION S12'),
        ('S13', 'SECTION S13'),
        ('S14', 'SECTION S14'),
        ('S15', 'SECTION S15'),
        ('S16', 'SECTION S16'),
    ]
    student = models.ForeignKey(StudentList, on_delete=models.CASCADE)
    course = models.CharField(max_length=50, choices=COURSE_CHOICES)
    section = models.CharField(max_length=50, choices=SECTION_CHOICES)

    def __str__(self):
        return f'{self.student.register_number} - {self.course} ({self.section})'

class Marks(models.Model):
    COURSE_CHOICES = [
        ('AOOP', 'Advanced Object-Oriented Programming'),
        ('PFSD', 'Python Full Stack Development'),
    ]
    student = models.ForeignKey(StudentList, on_delete=models.CASCADE)
    course = models.CharField(max_length=50, choices=COURSE_CHOICES)
    marks = models.IntegerField()
    def __str__(self):
        return f"{self.student.name}- {self.course}"

adminapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    title = models.CharField(max_length=200)
    created_Aty = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title





class StudentList(models.Model):
    Register_Number = models.CharField(max_length=20, unique=True)
    Name = models.CharField(max_length=100)
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.Register_Number


class Feedback(models.Model):
    username = models.CharField(max_length=100)
    email = models.EmailField()
    password = models.CharField(max_length=50)
    description = models.TextField()

    def __str__(self):
        return self.username

class Contact(models.Model):
    name = models.CharField(max_length=100)
    email=models.EmailField()
    phone_number=models.CharField(max_length=10)
    address = models.CharField(max_length=100)
    def __str__(self):
        return self.name

adminapp/studentapp/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

adminapp/facultyapp/forms.py
from django import forms
from .models import Post, AddCourse , Marks


class PostForm(forms.ModelForm):
    class Meta:
        model = Post  # Assuming your model is called Post
        fields = ['title', 'content']  # Include the fields you want to appear in the form
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter the title'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Write your post content here...'}),
        }

class AddCourseForm(forms.ModelForm):
    class Meta:
        model = AddCourse
        fields = ['student', 'course', 'section']

class MarksForm(forms.ModelForm):
    class Meta:
        model = Marks
        fields = ['student' , 'course' , 'marks']

adminapp/forms.py
from django import forms
from .models import Task, StudentList, Contact


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title']


class StudentForm(forms.ModelForm):
    class Meta:
        model = StudentList
        fields = ['Register_Number', 'Name']

class UploadFileForm(forms.Form):
    file = forms.FileField()

from .models import Feedback

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['username', 'email', 'password', 'description']

class ContactForm(forms.ModelForm):
    class Meta:
        model=Contact
        fields = ['name', 'email', 'phone_number', 'address']

adminapp/studentapp/forms.py
from django import forms
from django.shortcuts import redirect, render

from .models import StudentList


class StudentForm(forms.ModelForm):
    class Meta:
        model = StudentList
        fields = ['Register_Number', 'Name']

adminapp/facultyapp/views.py
from django.core.mail import send_mail
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post  # Assuming Post model is in faculty.models
from .forms import PostForm, MarksForm  # Assuming PostForm is in faculty.forms

def facultyhomepage(request):
    return render(request, 'facultyapp/FacultyHomePage.html')
def add_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('add_post')
    else:
        form = PostForm()
    posts = Post.objects.all()
    return render(request, 'facultyapp/blogPost.html', {'form': form, 'posts': posts})

def delete_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('add_post')


from .forms import AddCourseForm
def add_course(request):
    if request.method == 'POST':
        form = AddCourseForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('facultyapp:FacultyHomePage')
    else:
        form = AddCourseForm()
    return render(request, 'facultyapp/add_course.html', {'form': form})


from .models import AddCourse
from adminapp.models import StudentList

def view_student_list(request):
    course = request.GET.get('course')
    section = request.GET.get('section')
    student_courses = AddCourse.objects.all()
    if course:
        student_courses = student_courses.filter(course=course)
    if section:
        student_courses = student_courses.filter(section=section)
    students = StudentList.objects.filter(id__in=student_courses.values('student_id'))
    course_choices = AddCourse.COURSE_CHOICES
    section_choices = AddCourse.SECTION_CHOICES
    context = {
        'students': students,
        'course_choices': course_choices,
        'section_choices': section_choices,
        'selected_course': course,
        'selected_section': section,
    }
    return render(request, 'facultyapp/view_student_list.html', context)
def post_marks(request):
    if request.method == "POST":
        form = MarksForm(request.POST)
        if form.is_valid():
            marks_instance = form.save(commit=False)
            marks_instance.save()

            # Retrieve the User email based on the student in the form
            student = marks_instance.student
            student_user = student.user
            user_email = student_user.email

            subject = 'Marks Entered'
            message = f'Hello, {student_user.first_name}  marks for {marks_instance.course} have been entered. Marks: {marks_instance.marks}'
            from_email = 'ajayradha9989@gmail.com'
            recipient_list = [user_email]
            send_mail(subject, message, from_email, recipient_list,timeout=30)

            return render(request, 'facultyapp/marks_success.html')
    else:
        form = MarksForm()
    return render(request, 'facultyapp/post_marks.html', {'form': form})

adminapp/studentapp/views.py
from django.contrib import auth, messages
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.shortcuts import render

from adminapp.models import StudentList
from facultyapp.models import Marks


# Create your views here.

def studenthomepage(request):
    return render(request, 'facultyapp/StudentHomePage.html')


def UserLoginPageCall(request):
    return render(request, 'adminapp/Login.html')

def UserLoginLogic(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            auth.login(request, user)
            if len(username) == 10:
                # Redirect to StudentHomePage
                messages.success(request, 'Login successful as student!')
                return redirect('studentapp:StudentHomePage')  # Replace with your student homepage URL name
                return render(request, 'facultyapp/FacultyHomePage.html')
            elif len(username) == 4:
                # Redirect to FacultyHomePage
                messages.success(request, 'Login successful as faculty!')
                return redirect('facultyapp:FacultyHomePage')  # Replace with your faculty homepage URL name
                return render(request, 'facultyapp/FacultyHomePage.html')
            else:
                # Invalid username length
                messages.error(request, 'Username length does not match student or faculty criteria.')
                return render(request, 'adminapp/Login.html')
        else:
            # If authentication fails
            messages.error(request, 'Invalid username or password.')
            return render(request, 'adminapp/Login.html')
    else:
        return render(request, 'adminapp/Login.html')

def logout(request):
    auth.logout(request)
    return redirect('projecthomepage')

def student_list(request):
    students = StudentList.objects.all()
    return render(request, 'adminapp/student_list.html', {'students': students})

def view_marks(request):
    user=request.user
    try:
        student_user = User.objects.get(username=user.username)
        student = StudentList.objects.get(Register_Number=student_user)
        marks = Marks.objects.filter(student=student)
        return render(request,'studentapp/view_marks.html', {'marks':marks})
    except (StudentList.DoesNotExist, User.DoesNotExist):
        return render(request, 'studentapp/view_marks.html',{
            'error': 'No Student record found for this user.'
        })

adminapp/templates/adminapp/ExceptionExample.html
{% extends 'Navbar/Projectnavbar.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Implementation of Exception Handling</title>
</head>
<body>

{% block body %}
<div class="container text-center">
  <div class="row">
    <div class="col">
      First in DOM, ordered last
      <div>
        <br><br>
        <form method="post" action="{% url 'exceptionpagelogic' %}">
            {% csrf_token %}
            <label>Enter a Number:</label>
            <input type="text" name="user_input" required>
            <br><br>
            <div class="d-grid gap-2 col-6 mx-auto">
            <button class="btn btn-primary" type="submit">Submit</button>
            </div>
        </form>
      </div>
    </div>
      <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
      <br><br><br><br><br><br><br>
       <div class="col-auto d-flex align-items-center">
      <div style="border-left: 2px solid black; height: 100%;"></div>
    </div>
    <div class="col" >
        <br><br>
      <strong> Output will be displayed Here</strong>

      <h1>
        {% if result %}
        <h2>Result: {{ result }}</h2>
    {% elif error %}
        <h2 style="color: red;">Error: {{ error }}</h2>
    {% endif %}
      </h1>
    </div>
  </div>
</div>
{% endblock %}

</body>
</html>

adminapp/templates/adminapp/Login.html
{% extends 'Navbar/Projectnavbar.html' %}
{% load static %}

{% block body %}
    <div class="container d-flex justify-content-center align-items-center mt-5">
        <form method="POST" action="{% url 'login' %}" class="w-100" style="max-width: 400px;">
            {% csrf_token %}

            <!-- Display messages if any (like success or error notifications) -->
            {% if messages %}
                <ul>
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}

            <!-- Non-field errors (for general form validation issues) -->
            {% if form.non_field_errors %}
                <ul>
                    {% for error in form.non_field_errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            {% endif %}

            <h2 align="center">LOGIN</h2>

            <!-- Username input -->
            <div class="form-outline mb-4">
                <input type="text" id="username" name="username" class="form-control" required />
                <label class="form-label" for="username">Username</label>
            </div>

            <!-- Password input -->
            <div class="form-outline mb-4">
                <input type="password" id="password" name="password" class="form-control" required />
                <label class="form-label" for="password">Password</label>
            </div>

            <!-- Submit button -->
            <button type="submit" class="btn btn-primary btn-block mb-4">Sign in</button>
        </form>
    </div>
{% endblock %}

<style>
    body {
        background-color: #EEEEEE;
    }
    .navbar {
        background-color: white !important;
    }
    .nav-link:hover {
        text-decoration: underline;
    }
    .navbar-brand {
        margin-left: 90px;
    }
    .navname {
        margin-left: 20px;
    }
    .form-container {
        width: 400px !important;
        background-color: white;
        padding: 2.5rem;
        border-radius: 4px;
        box-shadow: 0 0 15px rgba(0, 0, 0, 0.1);
    }
    .form-container img {
        display: block;
        margin: 0 auto 2.5rem;
    }
    .form-control {
        height: 50px;
        padding: 0.75rem 1.25rem;
        margin-bottom: 2rem;
    }
</style>

adminapp/templates/adminapp/ProjectHomePage.html
<!DOCTYPE html>
{% extends 'Navbar/ProjectNavbar.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <title>Title</title>
</head>
<body >

{% block body %}
<h3 align="center"><b>K. SAI SADWIIK</b></h3>
<hr>
<h3 align="center">Hi, Getting ready to work on Projects using Django</h3>
<hr>
<div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static 'images/gojo.jpg' %}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{% static 'images/monkey-d-luffy-rubber-warrior-pirate.jpg' %}" class="d-block w-100" alt="...">
    </div>

    <div class="carousel-item">
      <img src="{% static 'images/madara 🔥.jpg' %}" class="d-block w-100" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
{% endblock %}
</body>
</html>

adminapp/templates/adminapp/Register.html
{% extends 'Navbar/Projectnavbar.html' %}
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Register</title>
    <style>
        body,
        html {
            height: 100%;
        }

        .container {
            min-height: 100vh;
            padding: 20px;
            /* Add padding to avoid touching the container edges */
        }
    </style>
</head>

<body>

    {% block body %}
    <div class="container d-flex justify-content-center align-items-center">
        <form method="POST" action="{% url 'UserRegisterLogic' %}" class="w-100" style="max-width: 400px;">
            {% csrf_token %}

            {% if messages %}
            <ul>
                {% for message in messages %}
                <li>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}

            <div data-mdb-input-init class="form-outline mb-4">
                <label class="form-label" for="username">Username</label>
                <input type="text" id="username" name="username" class="form-control" required />
            </div>

            <div data-mdb-input-init class="form-outline mb-4">
                <label class="form-label" for="first_name">First Name</label>
                <input type="text" id="first_name" name="first_name" class="form-control" required />
            </div>

            <div data-mdb-input-init class="form-outline mb-4">
                <label class="form-label" for="last_name">Last Name</label>
                <input type="text" id="last_name" name="last_name" class="form-control" required />
            </div>

            <div data-mdb-input-init class="form-outline mb-4">
                <label class="form-label" for="email">Email address</label>
                <input type="email" id="email" name="email" class="form-control" required />
            </div>

            <div data-mdb-input-init class="form-outline mb-4">
                <label class="form-label" for="password">Password</label>
                <input type="password" id="password" name="password" class="form-control" required />
            </div>

            <div data-mdb-input-init class="form-outline mb-4">
                <label class="form-label" for="password1">Confirm Password</label>
                <input type="password" id="password1" name="password1" class="form-control" required />
            </div>

            <div class="row mb-4">
                <div class="col d-flex justify-content-center">
                    <div class="form-check">
                        <input class="form-check-input" type="checkbox" value="" id="remember_me" checked />
                        <label class="form-check-label" for="remember_me"> Remember me </label>
                    </div>
                </div>
            </div>

            <button type="submit" data-mdb-button-init data-mdb-ripple-init class="btn btn-primary btn-block mb-4">Sign
                up</button>

            <div class="text-center">
                <p>Already Have an Account? <a href="">Login</a></p>

                <button type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-link btn-floating mx-1">
                    <i class="fab fa-facebook-f"></i>
                </button>

                <button type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-link btn-floating mx-1">
                    <i class="fab fa-google"></i>
                </button>

                <button type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-link btn-floating mx-1">
                    <i class="fab fa-twitter"></i>
                </button>

                <button type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-link btn-floating mx-1">
                    <i class="fab fa-github"></i>
                </button>
            </div>
        </form>
    </div>
    {% endblock %}

</body>

</html>

adminapp/templates/adminapp/To-Do-List.html
{% extends 'Navbar/Projectnavbar.html' %}
{% load static %}
<html>
<head>
    <title>To-Do List</title>
</head>
<body>
{% block body %}

<div class="container text-center">
  <div class="row">
    <div class="col">
      First in DOM, no order applied
        <br><br>
            <h1>Add Task</h1>
            <form method="post" action="{% url 'add_task' %}">{% csrf_token %}
            {{ form.as_p }}
            <br><br>
            <div class="d-grid gap-2 col-6 mx-auto">
            <button class="btn btn-primary" type="submit">Submit</button>
            </div>
        </form>
    </div>
      <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
      <br><br><br><br><br><br><br><br><br><br><br>
       <div class="col-auto d-flex align-items-center">
      <div style="border-left: 2px solid black; height: 100%;"></div>
    </div>
    <div class="col">
        <br><br>
        <strong> Output will be displayed Here</strong>
              <h2>Tasks</h2>
    <ul>
        {% for task in tasks %}
            <li>
                {{ task.title }}
                <a href="{% url 'delete_task' task.pk %}">Delete</a>
            </li>
        {% endfor %}
    </ul>
    </div>

  </div>
</div>







{% endblock %}
</body>
</html>

adminapp/templates/adminapp/calculator.html
{% extends 'Navbar/Projectnavbar.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SIMPLE CALCULATOR</title>
</head>
<body>

{% block body %}
<div class="container text-center">
  <div class="row">
    <div class="col">
      <h1>Simple Calculator</h1>
      <div>
        <br><br>
         <form method="post" action="{% url 'calculatorlogic' %}" >
        {% csrf_token %}
        <input type="number" name="num1" step="any" placeholder="Enter first number" required>
        <input type="number" name="num2" step="any" placeholder="Enter second number" required>
        <select name="operation" required>
            <option value="add">+</option>
            <option value="subtract">-</option>
            <option value="multiply">*</option>
            <option value="divide">/</option>
        </select>
        <button type="submit">Calculate</button>
    </form>
      </div>
    </div>
      <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
      <br><br><br><br><br><br><br>
       <div class="col-auto d-flex align-items-center">
      <div style="border-left: 2px solid black; height: 100%;"></div>
    </div>
    <div class="col" >
        <br><br>
      <strong> Output will be displayed Here</strong>

      <h1>
       {% if result is not None %}
    <h2>Result: {{ result }}</h2>
    {% endif %}
      </h1>
    </div>
  </div>
</div>
{% endblock %}

</body>
</html>

adminapp/templates/adminapp/chart.html
{% extends 'Navbar/ProjectNavbar.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Implementation of Exception Handling</title>
</head>
<body>

{% block body %}
<div class="container text-center">
  <div class="row">
    <div class="col">
      First in DOM, ordered last
      <div>
        <br><br>

<!-- templates/upload.html -->
<h2>Upload CSV File</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
</form>



      </div>
    </div>
      <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
      <br><br><br><br><br><br><br>
       <div class="col-auto d-flex align-items-center">
      <div style="border-left: 2px solid black; height: 100%;"></div>
    </div>
    <div class="col" >
        <br><br>
      <strong> Output will be displayed Here</strong>

<!-- templates/result.html -->
<h2>Sales Report</h2>
<p><strong>Total Sales:</strong> Rs.{{ total_sales }}</p>
<p><strong>Average Sales:</strong> Rs.{{ average_sales }}</p>

<h3>Sales Distribution Chart</h3>
<img src="data:image/png;base64,{{ chart }}" alt="Sales Chart">


    </div>
  </div>
</div>
{% endblock %}

</body>
</html>

adminapp/templates/adminapp/feedback_form.html
{% extends 'Navbar/Projectnavbar.html' %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <style>
        .container {
            margin-top: 50px;
            margin-left: 320px;
            margin-right: 50px;
        }
        .custom-form {
            max-width: 700px; /* Decrease the form width */
        }
        .description-area {
            height: 130px; /* Increase height for the description */
            resize: none; /* Prevent resizing */
        }
    </style>
</head>

<body>
 {% block body %}
    <div class="container">
        <div class="container-fluid">
            <form class="custom-form" method="POST" action="{% url 'feedback_form' %}">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="id_username" class="form-label">Username</label>
                    <input type="text" name="username" class="form-control" id="id_username" required>
                </div>
                <div class="mb-3">
                    <label for="id_email" class="form-label">Email address</label>
                    <input type="email" name="email" class="form-control" id="id_email" required>
                    <div id="emailHelp" class="form-text">
                        We'll never share your email with anyone else.
                    </div>
                </div>
                <div class="mb-3">
                    <label for="id_password" class="form-label">Password</label>
                    <input type="password" name="password" class="form-control" id="id_password" required>
                </div>
                <div class="mb-3">
                    <label for="id_description" class="form-label">Description</label>
                    <textarea name="description" class="form-control description-area" id="id_description" required></textarea>
                </div>
                <button type="submit"  class="btn btn-primary" href="{% url 'feedback_success' %}">Submit</button>
            </form>
        </div>
    </div>
 {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>