SMS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('adminapp.urls')),
    path('facultyapp/', include('facultyapp.urls')),
    path('studentapp/', include('studentapp.urls')),
]

adminapp/SMS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('adminapp.urls')),
    path('facultyapp/', include('facultyapp.urls')),
    path('studentapp/', include('studentapp.urls')),
]

facultyapp/urls.py
from django.urls import path, include
from . import views
app_name = 'facultyapp'
urlpatterns = [
    path('FacultyHomePage/', views.facultyhomepage, name="FacultyHomePage"),
    path('add_post/', views.add_post, name='add_post'),
    path('<int:pk>/delete/', views.delete_post, name='delete_post'),
    path('add_course/', views.add_course, name='add_course'),
    path('add_view_student_list/', views.view_student_list, name='add_view_student_list'),
    path('post_marks/', views.post_marks, name='post_marks'),
]

studentapp/urls.py
from django.urls import path, include
from . import views
app_name  ='studentapp'
urlpatterns=[
    path('StudentHomePage/',views.studenthomepage , name = "studenthomepage"),
    path('view_marks/',views.view_marks,name="view_marks"),

]

templates/Navbar/ProjectNavbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-primary bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand text-light" href="{% url 'projecthomepage' %}">SMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active text-light" aria-current="page" href="{% url 'projecthomepage' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-light" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-light" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            PFSD Concepts
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'printpagecall' %}">Printer</a></li>
            <li><a class="dropdown-item" href="{% url 'randompagecall' %}">OTP</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'calculatorpagecall' %}">Calculator</a></li>
            <li><a class="dropdown-item" href="{% url 'datetimepagecall' %}">Calendar</a></li>
            <li><a class="dropdown-item" href="{% url 'add_task' %}">To-Do-List</a></li>
            <li><a class="dropdown-item" href="{% url 'upload_file' %}">DATA ANALYSIS</a></li>
            <li><a class="dropdown-item" href="{% url 'feedback_form' %}">Feedback</a></li>


          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled text-light" aria-disabled="true">Disabled</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-light" href="{% url 'exceptionpagecall' %}">Exception Handling</a>
        </li>
      </ul>

      <form class="d-flex me-3" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-light " type="submit">Search</button>
      </form>

      <!-- Navbar Authentication Links -->
      <ul class="navbar-nav ms-auto">
        {% if user.is_authenticated %}
          <!-- If user is authenticated, show Welcome and Logout links -->
          <li class="nav-item">
            <span class="nav-link text-light">Welcome, {{ user.username }}</span>
          </li>
          <li class="nav-item">
            <a class="nav-link text-light" href="{% url 'logout' %}">Logout</a>
          </li>
        {% else %}
          <!-- If user is not authenticated, show Register and Login links -->
          <li class="nav-item">
            <a class="nav-link text-light" href="{% url 'UserRegisterPageCall' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-light" href="{% url 'login' %}">Login</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

{% block body %}
{% endblock %}

</body>
</html>

templates/Navbar/fac_navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-primary bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand text-light" href="{% url 'projecthomepage' %}">SMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active text-light" aria-current="page" href="{% url 'projecthomepage' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-light" href="{% url 'add_post' %}">BLOG POST</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-light" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            PFSD Concepts
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'add_details' %}">ADD STUDENT</a></li>
            <li><a class="dropdown-item" href="{% url 'show_details' %}">DISPLAY STUDENT DETAILS</a></li>
            <li><a class="dropdown-item" href="{% url 'facultyapp:add_course' %}">ADD COURSE</a></li>
            <li><a class="dropdown-item" href="{% url 'facultyapp:add_view_student_list' %}">STUDENT List</a></li>
            <li><a class="dropdown-item" href="{% url 'facultyapp:post_marks' %}">Mail Marks</a></li>
          </ul>
        </li>
      </ul>

      <form class="d-flex me-3" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-light " type="submit">Search</button>
      </form>

      <!-- Navbar Authentication Links -->
      <ul class="navbar-nav ms-auto">
        {% if user.is_authenticated %}
          <!-- If user is authenticated, show Welcome and Logout links -->
          <li class="nav-item">
            <span class="nav-link text-light">Welcome, {{ user.username }}</span>
          </li>
          <li class="nav-item">
            <a class="nav-link text-light" href="{% url 'logout' %}">Logout</a>
          </li>
        {% else %}
          <!-- If user is not authenticated, show Register and Login links -->
          <li class="nav-item">
            <a class="nav-link text-light" href="{% url 'UserRegisterPageCall' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-light" href="{% url 'login' %}">Login</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

{% block body %}
{% endblock %}

</body>
</html>

templates/Navbar/stud_navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-primary bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand text-light" href="{% url 'projecthomepage' %}">SMS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active text-light" aria-current="page" href="{% url 'projecthomepage' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-light" href="{% url 'add_post' %}">BLOG POST</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-light" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            PFSD Concepts
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'studentapp:view_marks' %}">VIEW_MARKS</a></li>

          </ul>
        </li>
      </ul>

      <form class="d-flex me-3" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-light " type="submit">Search</button>
      </form>

      <!-- Navbar Authentication Links -->
      <ul class="navbar-nav ms-auto">
        {% if user.is_authenticated %}
          <!-- If user is authenticated, show Welcome and Logout links -->
          <li class="nav-item">
            <span class="nav-link text-light">Welcome, {{ user.username }}</span>
          </li>
          <li class="nav-item">
            <a class="nav-link text-light" href="{% url 'logout' %}">Logout</a>
          </li>
        {% else %}
          <!-- If user is not authenticated, show Register and Login links -->
          <li class="nav-item">
            <a class="nav-link text-light" href="{% url 'UserRegisterPageCall' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-light" href="{% url 'login' %}">Login</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

{% block body %}
{% endblock %}

</body>
</html>